machines:
  # Bambu Lab
  - { family: bambu_corexy, id: bambu_a1_mini, model: "A1 Mini", enclosed: false, aliases: ["A1 mini"] }
  - { family: bambu_corexy, id: bambu_a1, model: "A1", enclosed: false }
  - { family: bambu_corexy, id: bambu_p1p, model: "P1P", enclosed: false }
  - { family: bambu_corexy, id: bambu_p1s, model: "P1S" }
  - { family: bambu_corexy, id: bambu_x1c, model: "X1 Carbon", capabilities: ["lidar_flow", "chamber_camera"] }
  - { family: bambu_corexy, id: bambu_x1e, model: "X1E" }
  - { family: bambu_corexy, id: bambu_p2s, model: "P2S" }
  - { family: bambu_corexy, id: bambu_h2d, model: "H2D" }
  - { family: bambu_corexy, id: bambu_h2s, model: "H2S" }

  # Prusa
  - { family: prusa_bedslinger, id: prusa_mk4, model: "Original Prusa MK4", aliases: ["MK4"] }
  - { family: prusa_bedslinger, id: prusa_mk3s_compat, model: "Original Prusa MK3S+", aliases: ["MK3S+"] }
  - { family: prusa_bedslinger, id: prusa_mini_plus, model: "Prusa Mini+", build_volume_mm: [180, 180, 180] }
  - { family: prusa_bedslinger, id: prusa_xl, model: "Prusa XL (Toolchanger)", motion_system: "CoreXY", build_volume_mm: [360, 360, 360], supports: { idex: false } }

  # Creality — CoreXY line
  - { family: creality_corexy, id: creality_k1c, model: "K1C" }
  - { family: creality_corexy, id: creality_k1_max, model: "K1 Max", build_volume_mm: [300, 300, 300] }
  - { family: creality_corexy, id: creality_k2_plus, model: "K2 Plus", build_volume_mm: [350, 350, 350] }

  # Creality — Bed slinger / others
  - { family: creality_bedslinger, id: creality_ender3_v3, model: "Ender-3 V3" }
  - { family: creality_bedslinger, id: creality_ender3_v3_plus, model: "Ender-3 V3 Plus", build_volume_mm: [300, 300, 300] }
  - { family: creality_bedslinger, id: creality_ender5_max, model: "Ender-5 Max", build_volume_mm: [350, 350, 400] }
  - { family: creality_bedslinger, id: creality_cr10_se, model: "CR-10 SE", build_volume_mm: [220, 220, 265] }
  - { family: creality_bedslinger, id: creality_cr_m4, model: "CR-M4", build_volume_mm: [450, 450, 470] }
  - { family: creality_bedslinger, id: creality_sermoon_d3, model: "Sermoon D3", enclosed: true }
  - { family: creality_bedslinger, id: creality_sermoon_d3_pro, model: "Sermoon D3 Pro", enclosed: true }
  - { family: creality_bedslinger, id: creality_sermoon_v1, model: "Sermoon V1", enclosed: true }

  # Anycubic Kobra 2 family
  - { family: anycubic_fdm, id: anycubic_kobra2, model: "Kobra 2" }
  - { family: anycubic_fdm, id: anycubic_kobra2_pro, model: "Kobra 2 Pro" }
  - { family: anycubic_fdm, id: anycubic_kobra2_plus, model: "Kobra 2 Plus", build_volume_mm: [320, 320, 400] }
  - { family: anycubic_fdm, id: anycubic_kobra2_max, model: "Kobra 2 Max", build_volume_mm: [420, 420, 500] }

  # ELEGOO Neptune
  - { family: elegoo_neptune, id: elegoo_neptune3, model: "Neptune 3" }
  - { family: elegoo_neptune, id: elegoo_neptune3_pro, model: "Neptune 3 Pro" }
  - { family: elegoo_neptune, id: elegoo_neptune4, model: "Neptune 4" }
  - { family: elegoo_neptune, id: elegoo_neptune4_pro, model: "Neptune 4 Pro" }
  - { family: elegoo_neptune, id: elegoo_neptune4_plus, model: "Neptune 4 Plus", build_volume_mm: [320, 320, 400] }
  - { family: elegoo_neptune, id: elegoo_neptune4_max, model: "Neptune 4 Max", build_volume_mm: [420, 420, 480] }

  # QIDI
  - { family: qidi_x_series, id: qidi_x_plus3, model: "X-Plus 3" }
  - { family: qidi_x_series, id: qidi_x_max3, model: "X-Max 3", build_volume_mm: [325, 325, 315] }

  # UltiMaker
  - { family: ultimaker_s_series, id: ultimaker_s5, model: "S5" }
  - { family: ultimaker_s_series, id: ultimaker_s7, model: "S7" }

  # Raise3D
  - { family: raise3d_pro, id: raise3d_pro3, model: "Pro3" }
  - { family: raise3d_pro, id: raise3d_e2, model: "E2" }
  - { family: raise3d_pro, id: raise3d_e2cf, model: "E2CF" }

  # Extras (popular community)
  - { family: extra_popular_fdm, id: artillery_sidewinder_x2, brand: "Artillery", model: "Sidewinder X2", motion_system: "BedSlinger", build_volume_mm: [300, 300, 400] }
  - { family: extra_popular_fdm, id: flsun_v400, brand: "FLSUN", model: "V400", motion_system: "Delta", build_volume_mm: [300, 300, 410] }
  - { family: extra_popular_fdm, id: voron_24_kit, brand: "Voron", model: "2.4 (Kit)", motion_system: "CoreXY", enclosed: true, build_volume_mm: [300, 300, 300], capabilities: ["input_shaping"] }

  # Formlabs
  - { family: formlabs_msla, id: formlabs_form4, model: "Form 4" }
  - { family: formlabs_msla, id: formlabs_form4b, model: "Form 4B" }
  - { family: formlabs_msla, id: formlabs_form4l, model: "Form 4L", build_volume_mm: [300, 200, 300] }

  # Prusa MSLA
  - { family: prusa_sl1s, id: prusa_sl1s_speed, model: "SL1S SPEED" }

  # Anycubic Photon
  - { family: anycubic_msla, id: anycubic_photon_mono_m5s, model: "Photon Mono M5s" }
  - { family: anycubic_msla, id: anycubic_photon_mono_m5s_pro, model: "Photon Mono M5s Pro" }

  # ELEGOO MSLA
  - { family: elegoo_msla, id: elegoo_mars4_ultra, model: "Mars 4 Ultra" }
  - { family: elegoo_msla, id: elegoo_saturn4, model: "Saturn 4" }
  - { family: elegoo_msla, id: elegoo_saturn4_ultra, model: "Saturn 4 Ultra" }

  # Phrozen
  - { family: phrozen_msla, id: phrozen_sonic_mighty_8k, model: "Sonic Mighty 8K" }

  # Carbide 3D Shapeoko 5 Pro
  - { family: carbide_shapeoko, id: shapeoko5pro_2x2, model: "Shapeoko 5 Pro (2x2)", workarea_mm: [610, 610, 100] }
  - { family: carbide_shapeoko, id: shapeoko5pro_4x2, model: "Shapeoko 5 Pro (4x2)", workarea_mm: [1219, 610, 100] }
  - { family: carbide_shapeoko, id: shapeoko5pro_4x4, model: "Shapeoko 5 Pro (4x4)", workarea_mm: [1219, 1219, 100] }

  # Onefinity Elite
  - { family: onefinity_elite, id: onefinity_woodworker_elite, model: "Onefinity Woodworker Elite", workarea_mm: [813, 813, 130] }
  - { family: onefinity_elite, id: onefinity_journeyman_elite, model: "Onefinity Journeyman Elite", workarea_mm: [1219, 813, 130] }
  - { family: onefinity_elite, id: onefinity_foreman_elite, model: "Onefinity Foreman Elite", workarea_mm: [1219, 1219, 130] }

  # Inventables X-Carve Pro
  - { family: inventables_xcarve, id: xcarve_pro_4x2, model: "X-Carve Pro 4x2", workarea_mm: [1219, 610, 100] }
  - { family: inventables_xcarve, id: xcarve_pro_4x4, model: "X-Carve Pro 4x4", workarea_mm: [1219, 1219, 100] }

  # Genmitsu
  - { family: genmitsu_router, id: genmitsu_3018, model: "Genmitsu 3018", workarea_mm: [300, 180, 45] }
  - { family: genmitsu_router, id: genmitsu_4040_pro_max, model: "Genmitsu 4040-PRO MAX", workarea_mm: [400, 400, 110] }

  # Bantam Tools
  - { family: bantam_desktop, id: bantam_desktop_cnc, model: "Bantam Tools Desktop CNC" }

  # Tormach
  - { family: tormach_pcnc, id: tormach_pcnc440, model: "PCNC 440", workarea_mm: [254, 165, 254] }

  # Haas Mini Mill (compact VMC)
  - { family: haas_mini_mill, id: haas_mini_mill, model: "Haas Mini Mill", workarea_mm: [406, 305, 254] }

  # Avid CNC PRO series
  - { family: avid_pro, id: avid_pro4896, model: "Avid PRO4896", workarea_mm: [1219, 2438, 152] }

  # STEPCRAFT D-Series
  - { family: stepcraft_d_series, id: stepcraft_d420, model: "STEPCRAFT D.420", workarea_mm: [400, 300, 140] }
  - { family: stepcraft_d_series, id: stepcraft_d600, model: "STEPCRAFT D.600", workarea_mm: [600, 400, 140] }
  - { family: stepcraft_d_series, id: stepcraft_d840, model: "STEPCRAFT D.840", workarea_mm: [840, 600, 140] }

  # MillRight Mega V2
  - { family: millright_megav2, id: millright_megav2_19x19, model: "Mega V2 (19x19)", workarea_mm: [483, 483, 89] }
  - { family: millright_megav2, id: millright_megav2_35x35, model: "Mega V2 (35x35)", workarea_mm: [889, 889, 89] }
  - { family: millright_megav2, id: millright_megav2_50x97, model: "Mega V2 (50x97)", workarea_mm: [1270, 2464, 89] }

  # Generic fallbacks
  - { family: generic_fdm_open, id: generic_fdm_open, model: "Generic Open FDM" }
  - { family: generic_fdm_enclosed, id: generic_fdm_enclosed, model: "Generic Enclosed FDM" }
  - { family: generic_msla_mid, id: generic_msla_mid, model: "Generic Mid-volume MSLA" }
  - { family: generic_router_hobby, id: generic_router_hobby, model: "Generic Hobby CNC Router" }
  - { family: generic_vmc, id: generic_vmc, model: "Generic VMC" }
