/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {string} */
              status: "ok";
              stub_inference: boolean;
              uptime_ms: number;
            };
          };
        };
      };
    };
  };
  "/_debug": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** @enum {string} */
              status: "ok";
              env: string;
              version: string;
              timestamp: string;
              uptime_ms: number;
              rate_limit: {
                requests: number;
                windowSeconds: number;
              };
              upload_max_mb: number;
              memory: {
                rss: number;
                heapUsed: number;
                heapTotal: number;
                external: number;
              };
              request_counters: {
                total: number;
                per_route: {
                  [key: string]: {
                    count: number;
                    last_request_ts: string | null;
                  };
                };
              };
            };
          };
        };
      };
    };
  };
  "/api/analyze-image": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              image_id: string;
              version: string;
              machine: {
                id: string;
                brand: string;
                model: string;
              };
              /** @enum {string} */
              experience: "Beginner" | "Intermediate" | "Advanced";
              material?: string;
              predictions: {
                  issue_id: string;
                  confidence: number;
                }[];
              explanations: string[];
              localization: {
                boxes: {
                    issue_id: string;
                    confidence: number;
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                  }[];
                heatmap?: {
                  /** @enum {string} */
                  encoding: "svg";
                  width: number;
                  height: number;
                  data_url: string;
                } | null;
              };
              capability_notes: string[];
              recommendations: string[];
              suggestions: ({
                  issue_id: string;
                  changes: ({
                      param: string;
                      delta?: number | null;
                      unit?: string | null;
                      new_target?: number | null;
                      range_hint?: number[] | null;
                    })[];
                  why: string;
                  risk: string;
                  confidence: number;
                  beginner_note?: string | null;
                  advanced_note?: string | null;
                  clamped_to_machine_limits?: boolean | null;
                })[];
              slicer_profile_diff?: {
                diff?: {
                  [key: string]: string | number | boolean;
                };
                parameters?: {
                  [key: string]: {
                    value?: number;
                    delta?: number;
                    unit?: string;
                    range_hint?: number[];
                    clamped?: boolean;
                  };
                };
                markdown?: string;
              };
              applied: {
                parameters: {
                  [key: string]: number;
                };
                hidden_parameters: string[];
                /** @enum {string} */
                experience_level: "Beginner" | "Intermediate" | "Advanced";
                clamped_to_machine_limits: boolean;
                explanations: string[];
              };
              low_confidence: boolean;
              parameter_targets: {
                [key: string]: number;
              };
              issues?: {
                  id: string;
                  confidence: number;
                }[];
              issue_list?: {
                  id: string;
                  confidence: number;
                }[];
              clamp_explanations?: string[];
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/analyze-json": {
    post: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              image_id: string;
              version: string;
              machine: {
                id: string;
                brand: string;
                model: string;
              };
              /** @enum {string} */
              experience: "Beginner" | "Intermediate" | "Advanced";
              material?: string;
              predictions: {
                  issue_id: string;
                  confidence: number;
                }[];
              explanations: string[];
              localization: {
                boxes: {
                    issue_id: string;
                    confidence: number;
                    x: number;
                    y: number;
                    width: number;
                    height: number;
                  }[];
                heatmap?: {
                  /** @enum {string} */
                  encoding: "svg";
                  width: number;
                  height: number;
                  data_url: string;
                } | null;
              };
              capability_notes: string[];
              recommendations: string[];
              suggestions: ({
                  issue_id: string;
                  changes: ({
                      param: string;
                      delta?: number | null;
                      unit?: string | null;
                      new_target?: number | null;
                      range_hint?: number[] | null;
                    })[];
                  why: string;
                  risk: string;
                  confidence: number;
                  beginner_note?: string | null;
                  advanced_note?: string | null;
                  clamped_to_machine_limits?: boolean | null;
                })[];
              slicer_profile_diff?: {
                diff?: {
                  [key: string]: string | number | boolean;
                };
                parameters?: {
                  [key: string]: {
                    value?: number;
                    delta?: number;
                    unit?: string;
                    range_hint?: number[];
                    clamped?: boolean;
                  };
                };
                markdown?: string;
              };
              applied: {
                parameters: {
                  [key: string]: number;
                };
                hidden_parameters: string[];
                /** @enum {string} */
                experience_level: "Beginner" | "Intermediate" | "Advanced";
                clamped_to_machine_limits: boolean;
                explanations: string[];
              };
              low_confidence: boolean;
              parameter_targets: {
                [key: string]: number;
              };
              issues?: {
                  id: string;
                  confidence: number;
                }[];
              issue_list?: {
                  id: string;
                  confidence: number;
                }[];
              clamp_explanations?: string[];
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        /** @description Default Response */
        500: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/machines": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              machines: {
                  id: string;
                  brand: string;
                  model: string;
                  type?: string;
                  aliases?: string[];
                  capabilities?: string[];
                  safe_speed_ranges?: {
                    print?: number[];
                    travel?: number[];
                    accel?: number[];
                    jerk?: number[];
                  };
                  max_nozzle_temp_c?: number;
                  max_bed_temp_c?: number;
                  spindle_rpm_range?: number[];
                  max_feed_mm_min?: number;
                  material_presets?: {
                    [key: string]: unknown;
                  };
                  notes?: string;
                  [key: string]: unknown;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/export-profile": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            slicer: string;
            changes: {
              [key: string]: string | number | boolean;
            };
            base_profile?: {
              [key: string]: string | number | boolean;
            };
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              slicer: string;
              diff: {
                [key: string]: string | number | boolean;
              };
              markdown?: string;
            };
          };
        };
        /** @description Default Response */
        400: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
